# Generated by Django 4.0 on 2021-12-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_date_of_birth_alter_employee_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='work_book',
            field=models.CharField(max_length=9, verbose_name='Number of the work book'),
        ),
    ]
