# Generated by Django 4.0 on 2021-12-25 16:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employee_work_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='work_book',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(regex='[А-Я]{2}\\d{7}$')], verbose_name='Number of the work book'),
        ),
    ]
