# Generated by Django 4.0 on 2021-12-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_employee_work_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(null=True, upload_to='', verbose_name='photo'),
        ),
    ]
