# Generated by Django 4.0 on 2021-12-26 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0001_initial'),
        ('employees', '0007_remove_employee_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='name',
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Role name')),
                ('performance_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.poster')),
            ],
        ),
        migrations.AddField(
            model_name='role',
            name='role_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='employees.roles'),
            preserve_default=False,
        ),
    ]
