# Generated by Django 4.0 on 2021-12-26 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0001_initial'),
        ('employees', '0008_remove_role_name_roles_role_role_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='performance_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.performance'),
        ),
    ]
