# Generated by Django 4.0 on 2021-12-31 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0004_alter_rating_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genre',
            field=models.CharField(max_length=32, verbose_name='Name of genre'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Description of a rating'),
        ),
    ]
