from django.contrib import admin
from django.urls import path
from employees import views


admin.autodiscover()

urlpatterns = [
<<<<<<< HEAD
    path('', views.main, name='employee'),
    path('/sort_roles_id_asc/', views.sort_roles_id_asc, name='sort_roles_id_asc'),
    path('/sort_roles_id_desc/', views.sort_roles_id_desc, name='sort_roles_id_desc'),
    path('/sort_roles_name_asc/', views.sort_roles_name_asc, name='sort_roles_name_asc'),
    path('/sort_roles_name_desc/', views.sort_roles_name_desc, name='sort_roles_name_desc'),
    path('/sort_roles_surname_asc/', views.sort_roles_surname_asc, name='sort_roles_surname_asc'),
    path('/sort_roles_surname_desc/', views.sort_roles_surname_desc, name='sort_roles_surname_desc'),
    path('/sort_roles_role_asc/', views.sort_roles_role_asc, name='sort_roles_role_asc'),
    path('/sort_roles_role_desc/', views.sort_roles_role_desc, name='sort_roles_role_desc'),
    path('/sort_roles_performance_asc/', views.sort_roles_performance_asc, name='sort_roles_performance_asc'),
    path('/sort_roles_performance_desc/', views.sort_roles_performance_desc, name='sort_roles_performance_desc'),
    path('/sort_roles_fee_asc/', views.sort_roles_fee_asc, name='sort_roles_fee_asc'),
    path('/sort_roles_fee_desc/', views.sort_roles_fee_desc, name='sort_roles_fee_desc'),
    path('/sort_positions_id_asc/', views.sort_positions_id_asc, name='sort_positions_id_asc'),
    path('/sort_positions_id_desc/', views.sort_positions_id_desc, name='sort_positions_id_desc'),
    path('/sort_positions_name_asc/', views.sort_positions_name_asc, name='sort_positions_name_asc'),
    path('/sort_positions_name_desc/', views.sort_positions_name_desc, name='sort_positions_name_desc'),
    path('/sort_hiring_id_asc/', views.sort_hiring_id_asc, name='sort_hiring_id_asc'),
    path('/sort_hiring_id_desc/', views.sort_hiring_id_desc, name='sort_hiring_id_desc'),
    path('/sort_hiring_name_asc/', views.sort_hiring_name_asc, name='sort_hiring_name_asc'),
    path('/sort_hiring_name_desc/', views.sort_hiring_name_desc, name='sort_hiring_name_desc'),
    path('/sort_hiring_surname_asc/', views.sort_hiring_surname_asc, name='sort_hiring_surname_asc'),
    path('/sort_hiring_surname_desc/', views.sort_hiring_surname_desc, name='sort_hiring_surname_desc'),
    path('/sort_hiring_position_asc/', views.sort_hiring_position_asc, name='sort_hiring_position_asc'),
    path('/sort_hiring_position_desc/', views.sort_hiring_position_desc, name='sort_hiring_position_desc'),
    path('/sort_hiring_date_asc/', views.sort_hiring_date_asc, name='sort_hiring_date_asc'),
    path('/sort_hiring_date_desc/', views.sort_hiring_date_desc, name='sort_hiring_date_desc'),
    path('/sort_roles_list_id_asc/', views.sort_roles_list_id_asc, name='sort_roles_list_id_asc'),
    path('/sort_roles_list_id_desc/', views.sort_roles_list_id_desc, name='sort_roles_list_id_desc'),
    path('/sort_roles_list_name_asc/', views.sort_roles_list_name_asc, name='sort_roles_list_name_asc'),
    path('/sort_roles_list_name_desc/', views.sort_roles_list_name_desc, name='sort_roles_list_name_desc'),
    path('/sort_roles_list_performance_asc/', views.sort_roles_list_performance_asc, name='sort_roles_list_perform_asc'),
    path('/sort_roles_list_performance_desc/', views.sort_roles_list_performance_desc, name='sort_roles_list_perform_desc'),
    path('/sort_employees_name_asc/', views.sort_employees_name_asc, name='sort_employees_name_asc'),
    path('/sort_employees_name_desc/', views.sort_employees_name_desc, name='sort_employees_name_desc'),
    path('/sort_employees_id_asc/', views.sort_employees_id_asc, name='sort_employees_id_asc'),
    path('/sort_employees_id_desc/', views.sort_employees_id_desc, name='sort_employees_id_desc'),
    path('/sort_employees_surname_asc/', views.sort_employees_surname_asc, name='sort_employees_surname_asc'),
    path('/sort_employees_surname_desc/', views.sort_employees_surname_desc, name='sort_employees_surname_desc'),
    path('/sort_employees_patronymic_asc/', views.sort_employees_patronymic_asc, name='sort_employees_patronymic_asc'),
    path('/sort_employees_patronymic_desc/', views.sort_employees_patronymic_desc, name='sort_employees_patronymic_desc'),
    path('/sort_employees_date_asc/', views.sort_employees_date_asc, name='sort_employees_date_asc'),
    path('/sort_employees_date_desc/', views.sort_employees_date_desc, name='sort_employees_date_desc'),
    path('/sort_employees_email_asc/', views.sort_employees_email_asc, name='sort_employees_email_asc'),
    path('/sort_employees_email_desc/', views.sort_employees_email_desc, name='sort_employees_email_desc'),
    path('/sort_employees_phone_asc/', views.sort_employees_phone_asc, name='sort_employees_phone_asc'),
    path('/sort_employees_phone_desc/', views.sort_employees_phone_desc, name='sort_employees_phone_desc'),
    path('/sort_employees_address_asc/', views.sort_employees_address_asc, name='sort_employees_address_asc'),
    path('/sort_employees_address_desc/', views.sort_employees_address_desc, name='sort_employees_address_desc'),
    path('/sort_employees_workbook_asc/', views.sort_employees_workbook_asc, name='sort_employees_workbook_asc'),
    path('/sort_employees_workbook_desc/', views.sort_employees_workbook_desc, name='sort_employees_workbook_desc'),
    path('employees/<int:pk>/update/', views.EmployeeUpdateView.as_view(), name='employee_update'),
    path('employees/<int:pk>/delete/', views.EmployeeDeleteView.as_view(), name='employee_delete'),
    path('employees/<int:pk>', views.EmployeeDetailView.as_view(), name='employee_info'),
    path('hiring/<int:pk>/update/', views.HiringUpdateView.as_view(), name='hiring_update'),
    path('hiring/<int:pk>/delete/', views.HiringDeleteView.as_view(), name='hiring_delete'),
    path('hiring/<int:pk>', views.HiringDetailView.as_view(), name='hiring_info'),
    path('roles_list/<int:pk>/update/', views.RolesListUpdateView.as_view(), name='roles_list_update'),
    path('roles_list/<int:pk>/delete/', views.RolesListDeleteView.as_view(), name='roles_list_delete'),
    path('roles_list/<int:pk>', views.RolesListDetailView.as_view(), name='roles_list_info'),
    path('positions/<int:pk>/update/', views.PositionsUpdateView.as_view(), name='positions_update'),
    path('positions/<int:pk>/delete/', views.PositionsDeleteView.as_view(), name='positions_delete'),
    path('positions/<int:pk>', views.PositionsDetailView.as_view(), name='positions_info'),
    path('roles/<int:pk>/update/', views.RolesUpdateView.as_view(), name='roles_update'),
    path('roles/<int:pk>/delete/', views.RolesDeleteView.as_view(), name='roles_delete'),
    path('roles/<int:pk>', views.RolesDetailView.as_view(), name='roles_info'),
    path('create_employee/', views.create_employee, name='create_employee'),
    path('create_position/', views.create_position, name='create_position'),
    path('create_role/', views.create_role, name='create_role'),
    path('create_role_list/', views.create_role_list, name='create_role_list'),
    path('create_hiring/', views.create_hiring, name='create_hiring'),
    path('employees/', views.employees, name='employees'),
    path('roles_list/', views.roles_list, name='roles_list'),
    path('hiring/', views.hiring, name='hiring'),
    path('roles/', views.roles, name='roles'),
    path('positions/', views.positions, name='positions')
=======
    path('', views.index, name = 'employees_main'),
    path('employees', views.employees, name='employees'),
    path('hiring', views.hiring, name='hiring'),
    path('roles', views.roles, name='roles')
>>>>>>> 2e166d30e963d225d123d3ad03c11980f04e4c4d
]