# Generated by Django 4.0 on 2021-12-31 07:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('performance', '0005_alter_genre_genre_alter_rating_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('phone', phone_field.models.PhoneField(max_length=31, validators=[django.core.validators.RegexValidator(regex='^((8|\\+7)[\\- ]?)?(\\(?\\d{3}\\)?[\\- ]?)?[\\d\\- ]{7,10}$')], verbose_name='Phone')),
                ('mail', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(regex='[a-z0-9]+@[a-z]+\\.[a-z]{2,3}')], verbose_name='Mail')),
                ('date', models.DateField(verbose_name='Date of order')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Order price')),
                ('cc_number', models.DecimalField(decimal_places=0, max_digits=16, validators=[django.core.validators.RegexValidator(regex='[0-9]+[0-9]+[0-9]+[0-9]+[0-9]+[0-9]+[0-9]+[0-9]+[0-9]+[0-9]+[0-9]+[0-9]+[0-9]+[0-9]+[0-9]+[0-9]')], verbose_name='card number')),
                ('cc_expiry', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(regex='[0-9]+[0-9]+/[0-9]+[0-9]')], verbose_name='expiration date')),
                ('cc_code', models.DecimalField(decimal_places=0, max_digits=3, validators=[django.core.validators.RegexValidator(regex='[1-9]+[0-9]+[0-9]')], verbose_name='security code')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket_ordered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Ticket price')),
                ('place', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('tier_id', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketStore.order')),
                ('poster_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.poster')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Ticket price')),
                ('place', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('availability', models.BooleanField(verbose_name='Availability')),
                ('poster_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.poster')),
                ('tier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.tier')),
            ],
        ),
    ]
