# Generated by Django 4.0 on 2021-12-25 15:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Ticket price')),
                ('place', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('availability', models.BooleanField(verbose_name='Availability')),
                ('poster_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.poster')),
                ('tier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.tier')),
            ],
        ),
    ]
